// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjvthdgxyxigwjtcbwot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqdnRoZGd4eXhpZ3dqdGNid290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDQ5MDYsImV4cCI6MjA3NzcyMDkwNn0.AhY62jsZxUbv2YlHC7M3NAnMV-XsDxrb_CRUYGxNhyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});